### ISSUE TITLE
weak tools or not?!

### ISSUE THREAD

**Issue by mahaase** [BobBuildTool/basement#104]
https://github.com/BobBuildTool/basement/blob/80378052dcfafd5d11e5a3e68a74c05337520058/recipes/devel/doxygen.yaml#L12

hey what do u think, should we define some of that tools as weaktool?
It came up to me, because of pipython3, everytime i change something there, also doxygen will be rebuilt, but i guess, in the end, the result shall be the same, isn't it?

**Comment by jkloetzke** [comment]
This really depends on the doxygen build system and why it needs python3. Do you know why doxygen needs python3? If it's only used to execute some scripts then it could be indeed a weak tool...

**Comment by mahaase** [comment]
i searched this: 
https://github.com/doxygen/doxygen/search?l=CMake&q=python

just the "PythonInterp" (PYTHON_EXECUTABLE) is used inside the project, not the "PythonLib". so python is a weak tool IMO.
I will make a PR.
