### ISSUE TITLE
zip (deflate) support in cmake

### ISSUE THREAD

**Issue by mahaase** [BobBuildTool/basement#118]
https://github.com/BobBuildTool/basement/blob/96dd3157071eab3e7fc361e15e510afb61f5c09a/recipes/libs/libarchive.yaml#L28

hey,

should we enable the zlib in libarchive to support zip (deflate) in cmake?

there are projects, that use https://cmake.org/cmake/help/latest/module/ExternalProject.html e.g.:

```
ExternalProject_Add(secretsauce
  URL                     https://www.somecompany.com/downloads/sauce-2.7.zip
  URL_HASH          MD5=d41d8cd98f00b204e9800998ecf8427e
...
)
```
which isn't supported yet.

**Comment by jkloetzke** [comment]
> should we enable the zlib in libarchive to support zip (deflate) in cmake?

Sure.
