### ISSUE TITLE
kernel::linux-image cannot be built for AArch64

### ISSUE THREAD

**Issue by jkloetzke** [BobBuildTool/basement#12]
```
make[1]: *** No rule to make target 'bzImage'.  Stop.
```

**Comment by Ferruck** [comment]
We may already have a fix for that [here](https://github.com/edeX-UG/basement/commit/48215cb3948e18d9062469acc478d30166cfe3a5). May you have a look?

**Comment by jkloetzke** [comment]
Looks like an immediate solution for AArch64. But I'm wondering if there is a generic solution for all architectures supported by the kernel... :thinking:

**Comment by Ferruck** [comment]
Is there any other architecture besides AArch64 that's using Image instead of bzImage, yet? Alas, it's a bit hard to search for the topic...
