### ISSUE TITLE
hard coded toolchain name

### ISSUE THREAD

**Issue by mahaase** [BobBuildTool/basement#127]
https://github.com/BobBuildTool/basement/blob/225b0b5e53f609f50345347e307b82eff10cb3a8/recipes/libs/glibc.yaml#L37

we should handle this by a variable defined in `cross-toolchain.yaml`

**Comment by jkloetzke** [comment]
Actually not really. This is only used if the multilib feature is enabled, i.e. build a toolchain that supports 32- and 64-bit simultaneously. Right now this is only supported on x86_64. If we would support other architectures with multilib too then this would need to be changed, indeed.
