### ISSUE TITLE
Adding an Ada compiler

### ISSUE THREAD

**Issue by Ferruck** [BobBuildTool/basement#14]
I think of adding GCC's Ada frontend to the basement. Alas, to build it, you already need the GNAT compiler, in a more or less specific version:

> Similarly, it is strongly recommended to use an older version of GNAT to build GNAT. [...]

In other words, with the currently installed Ada compiler on my Arch host I couldn't (or at least shouldn't) compile the first stage Ada compiler that comes with the basement.

Any ideas on how to tackle this? Should I use a pre-compiled Ada compiler from their website in order to compile the first stage? Or try to use the host, add a line to the `README.md` and hope for the best? Is Ada considered valuable enough, at all?

**Comment by jkloetzke** [comment]
Generally speaking I'm fully open to support other languages as long as it's reasonably maintainable.

If GNAT has specific requirements on the host then there is nothing we can do about it I guess. Is there any pre-compiled Ada compiler on the internet that we could use? Otherwise we have to live with the initial requirement. It may be possible to compile GNAT with the host-compat toolchain in the end so that everybody can use the pre-built version in the end...

**Comment by Ferruck** [comment]
Well, there's https://www.adacore.com/download. I haven't checked the license yet, but I guess it's quite permissive. So this could be included, probably the 32-bit Linux version? Or does the Windows support already matter for the basement?

**Comment by jkloetzke** [comment]
Maybe that could be the bootstrap requirement to get the GNAT version compiled. I wouldn't include it directly in basement because it doesn't fit the spirit of the project, though.

**Comment by Ferruck** [comment]
Maybe I'd rather create an Ada layer then. Having to install that as a dependency seems a bit overkill IMHO.

**Comment by jkloetzke** [comment]
Hmm, I would assume you only need Ada installed if your recipes actually use the Ada compiler. The existing toolchains wouldn't be impacted, would they?

**Comment by Ferruck** [comment]
If you combine it with a config switch, that'd be possible, I think. We'd still have to provide both versions of the artifacts in order for the artifact download to keep functioning.

**Comment by jkloetzke** [comment]
Then I guess it's better to have a separate mix-in-layer for the Ada compiler...
