### ISSUE TITLE
libs/expat fails at cross-compilation

### ISSUE THREAD

**Issue by mahaase** [BobBuildTool/basement#143]
the host-toolchain is missing as buildTool.

**Comment by Ferruck** [comment]
It cross-compiles fine here for `aarch64`...

**Comment by jkloetzke** [comment]
@mahaase Could you attach the relevant log.txt of the failed build of the package? It's strange that it does not compile in your case while it builds fine for @Ferruck ...

**Comment by mahaase** [comment]
retestet, not needed anymore.
