### ISSUE TITLE
libs/libcap fails at cross-compiling

### ISSUE THREAD

**Issue by mahaase** [BobBuildTool/basement#144]
if cross-compiling we have to set the `BUILD_CC` variable too.

**Comment by Ferruck** [comment]
Works here for `aarch64`. As we're hitting such situations (packages cross-compiling fine in one recipe stack and not at all in the next) regularly, I'd really like to understand the core problem...

**Comment by mahaase** [comment]
i will provide some more information. my use-case is the feature, i call "generic sandbox".

is it possible to see this diffs?
https://github.com/BobBuildTool/basement/compare/master...mahaase:feature/aarch64Sandbox?expand=1

that is the full diff-set i developed to get up this generic sandbox.

with that changes it is possible to setup a non-host-architecture sandbox
```
            # this is just an example how to use this sandbox inside a recipe
            SANDBOX_AUTOCONF_HOST: "aarch64-bob-linux-gnu"
            SANDBOX_AUTOCONF_BUILD: "aarch64-bob-linux-gnu"
            SANDBOX_AUTOCONF_TARGET: "aarch64-bob_compat-linux-gnu"
            SANDBOX_ARCH: "arm64"
```
this is extremly cool if u have embedded devices that have to power to build software on the target.
so we can provide artifacts, built on jenkins with that sandbox, to bob on the embedded device.

maybe some changes are not necessary anymore, i have to re-test it for that cases.

**Comment by mahaase** [comment]
so what do u think about the changes in glibc by adding the patch recipes/libs/compat/glibc/0004-aarch64-rewrite-emla-dynamic-symbol.diff. is this also deprecated/unneeded?

**Comment by jkloetzke** [comment]
Could you shed some light on the exact failure? Especially because @Ferruck is able to cross-compile it to aarch64... I haven't looked at the foreign architecture sandbox but I suspect a subtle problem there...

**Comment by mahaase** [comment]
this one is already fixed by @Ferruck https://github.com/BobBuildTool/basement/commit/52270a5ca487ceed6a723e2eae59893326c327ef 👍
