### ISSUE TITLE
wrong syntax

### ISSUE THREAD

**Issue by mahaase** [BobBuildTool/basement#15]
https://github.com/BobBuildTool/basement/blob/6878d4e8276588e353a7b962a32d9e1d22e8044a/classes/make.yaml#L5

```
- make -j "${MAKE_JOBS-$(nproc)}" "$@"
+ make -j "${MAKE_JOBS:-$(nproc)}" "$@"
```

same here:
https://github.com/BobBuildTool/basement/blob/c2a5d96fdba5d990666fb9d662248e8370c5bd25/recipes/devel/cmake.yaml#L61

BR.

**Comment by jkloetzke** [comment]
What's exactly wrong? The syntax is valid bash AFAICT.

**Comment by mahaase** [comment]
really, not missing a ":" in front of the "-"?

**Comment by jkloetzke** [comment]
Am 27. Juli 2020 15:29:05 MESZ schrieb Martin Haase <notifications@github.com>:
>really, not missing a ":" in front of the "-"?

No, not really. The colon makes the difference if the variable is defined but empty. See https://www.tldp.org/LDP/abs/html/parameter-substitution.html

**Comment by mahaase** [comment]
waahh! hkay! sry! xD
