### ISSUE TITLE
fingerprint check on MSYS2

### ISSUE THREAD

**Issue by mahaase** [BobBuildTool/basement#152]
https://github.com/BobBuildTool/basement/blob/952c467bbe1d617f1c019d493c6cde9acd698dfd/recipes/devel/host-compat-toolchain.yaml#L49-L73

'x86_64\nmsys-2.0/19.3003.5\nx86_64\nlibstdc++ 20220421\n'

I guess the checks are not working 100% correctly on MSYS2. We have unexpected artifact mismatches if the first part (`msys-2.0/19.3003.5`) is updated by MSYS2 updates.

**Comment by mahaase** [comment]
like i realized, the attached code isn't the problem. MSYS2 doesn't uses `host-compat-toolchain`, but just the `bootstrap-host-toolchain`.

but the problem still remains. an artifact built with e.g. `msys-2.0/19.3002.0` doesn't matches to a system with `msys-2.0/19.3003.5`

**Comment by jkloetzke** [comment]
> but the problem still remains. an artifact built with e.g. `msys-2.0/19.3002.0` doesn't matches to a system with `msys-2.0/19.3003.5`

This is working as intended. There is no magic version comparison baked into the fingerprinting stuff. If the fingerprint script produces a different output then the artifact will be stored/searched under a different build-id. Everything else would require a real database and code to compare versions numbers. It was a deliberate design decision to *not* do it this way.

> or is it up to me, to provide the tools for every msys2 version?

Unfortunately yes. Everything else is not entirely safe. Theoretically you could let the fingerprint script output just the major versions. But then you really must be sure that *all* future releases with the same major version are forward *and* backward compatible. I wouldn't make this bet TBH.

> how this works for the `devel::host-compat-toolchain` on linux?

The compat toolchain is using an ancient libc/libstdc++ and the fingerprint script will just make sure that the host is compatible. If you set `BASEMENT_HOST_COMPAT_TOOLCHAIN` to `0` then all host tools will also depend on the exact libc/libstdc++ version of your host just like on MSYS...

**Comment by mahaase** [comment]
Thanks for the explanations! I understand this - makes also sense to me 😉
I know what's to do now to handle this!
