### ISSUE TITLE
fakeroot 1.28 doesn't exists upstream anymore

### ISSUE THREAD

**Issue by mahaase** [BobBuildTool/basement#155]
https://github.com/BobBuildTool/basement/blob/b7c6482cf66c0c67f9e684a11ac5d8cb1b7df03d/recipes/devel/fakeroot.yaml#L4-L15

no idea, but they have removed it upstream... 🙄
what shall we do? upgrade to 1.29 or searching for a mirror?

**Comment by jkloetzke** [comment]
The upstream repo seems to be https://salsa.debian.org/clint/fakeroot. I guess we should clone from there. Updating is certainly a good idea but should be a separate commit...

**Comment by mahaase** [comment]
hm. i added a pull-request. but just updated the file version. i wouldn't change the recipe to git clone. hopefully they will not delete this version on fileserver again.

**Comment by jkloetzke** [comment]
Ok. Let's hope for the best.
