### ISSUE TITLE
host toolchain doesn't work for aarch64 systems

### ISSUE THREAD

**Issue by mahaase** [BobBuildTool/basement#162]
host-autoconf returns `arm64-linux-gnu` and fails while checking against `gcc -dumpmachine`

`Expected a compatible (arm64-linux-gnu) host compiler!`

the host-compiler is called `aarch64-linux-gnu`.

https://github.com/BobBuildTool/basement/blob/1579c4004605d8d15cc66843fd0c9f74d320e2a5/default.yaml#L20-L22

https://github.com/BobBuildTool/basement/blob/1579c4004605d8d15cc66843fd0c9f74d320e2a5/plugins/multiarch.py#L8-L38

**Comment by jkloetzke** [comment]
Yeah, the `host-autoconf` string function obviously needs fixing. I'm afraid that won't be the only problem. But let's see...

**Comment by jkloetzke** [comment]
Could you please test #163 and see if it fixes your problem?

**Comment by KKuerschner** [comment]
Your fix is working perfect.
