### ISSUE TITLE
add sysroot to find_root_path for all *gcc

### ISSUE THREAD

**Issue by daxcore** [BobBuildTool/basement#170]
https://github.com/BobBuildTool/basement/blob/f27d80635d624c398982e21135b7bbfc626cbdd3/classes/cmake.yaml#L18

I guess we should check for:

```
if [[ "$CC" == *"gcc" ]] ; then
```

I have some recipes, where i had to add sysroot manually to find_root_path.

**Comment by jkloetzke** [comment]
Makes sense. Would you mind creating a pull request?
