### ISSUE TITLE
python3-usr: PYTHONPATH of current build dir is missing

### ISSUE THREAD

**Issue by mahaase** [BobBuildTool/basement#172]
https://github.com/BobBuildTool/basement/blob/9bd2604ecf81f0680597545967618f759828a158/classes/python3-usr.yaml#L7

the current build directory has just something like that:

`[libs::something-dev]=/invalid/exec/path/of/libs::something-dev`

so it is not possible to use pip installed stuff in the current buildScript.

UPDATE:
https://github.com/BobBuildTool/basement/blob/9bd2604ecf81f0680597545967618f759828a158/classes/python3-usr.yaml#L10

now i realized, that just existing paths are added. so we have to add them when pip install was called already!

in my blueprint/prototype i added all paths, if they are existing or not.

**Comment by jkloetzke** [comment]
I'm not sure I understand the problem correctly. Why do you need to add the paths in the current workspace? Do you want to build some python package and execute it immediately? Wouldn't this then be more appropriate for the `python3-pkg` class to add? Especially because it locally built python packages will be under `install/`...

**Comment by mahaase** [comment]
i want to do something like that:

```
buildScript: |
    python3InstallPip something
    [python3 will need something]
```

in pipython3 layer i did this to solve the problem:

```
    PYTHONROOTDIR=${PWD}/install

    PYTHONPATH="${PYTHONPATH:+$PYTHONPATH}"
    for j in "" "lib-dynload" "site-packages" "dist-packages" ; do
        PYTHONPATH="${PYTHONROOTDIR}$PYTHONDESTLIB${j:+/$j}${PYTHONPATH:+:$PYTHONPATH}"
    done
    export PYTHONPATH
    export PYTHONROOTDIR

    pipInstall()
    {
        # force lib instead of Lib for MSYS
        mkdir -p ${PYTHONROOTDIR}/usr/lib
        python3 -m pip install -q $* \
            --root ${PYTHONROOTDIR} \
            --prefix usr \
            --disable-pip-version-check \
            --no-warn-script-location \
            --ignore-installed
    }
```

i just added all possible paths, unless if it will exists or not. currently in the `python3-pkg` class just paths of dependencies are handled/added.
