### ISSUE TITLE
CMAKE_BUILD_TYPE Bob?

### ISSUE THREAD

**Issue by mahaase** [BobBuildTool/basement#19]
https://github.com/BobBuildTool/basement/blob/6878d4e8276588e353a7b962a32d9e1d22e8044a/classes/cmake.yaml#L85

why cmake build type value is set to "Bob"?

**Comment by jkloetzke** [comment]
The same reason why the meson class uses `--buildtype plain`. All CFLAGS are controlled in the recipes and cmake should not add any flags on its own. There are the `BASEMENT_OPTIMIZE` and `BASEMENT_DEBUG` switches that control the result of all packages, regardless of the underlying build system.

**Comment by mahaase** [comment]
interesting, thanks. i have to think about that ;)
