### ISSUE TITLE
gawk: ar: Command not found

### ISSUE THREAD

**Issue by mahaase** [BobBuildTool/basement#2]
Hey,

I try to build this project, but I have the following issue.
gawk will be built twice. first one is working fine:

ar cru libsupport.a dfa.o getopt.o getopt1.o localeinfo.o random.o regex.o 
ar: `u' modifier ignored since `D' is the default (see `U')
x86_64-wendy-linux-gnu-ranlib libsupport.a

second one failes:

ar cru libsupport.a dfa.o getopt.o getopt1.o localeinfo.o random.o regex.o 
make[2]: ar: Command not found

here x86_64-bob-linux-gnu-gcc  is used.

Any ideas?

**Comment by mahaase** [comment]
like used in other recipes, I added -o "AR=$AR" to fix that.

**Comment by jkloetzke** [comment]
Where did you have to add "AR=$AR"? I've rebuilt `containers::lighttpd/` but didn't encounter any issues...
