### ISSUE TITLE
mirror list

### ISSUE THREAD

**Issue by mahaase** [BobBuildTool/basement#23]
https://github.com/BobBuildTool/basement/blob/6878d4e8276588e353a7b962a32d9e1d22e8044a/default.yaml#L2

here we are at the point, we would need the mirror-list feature. 
the companies using the basement may want to have an internal mirror of the archives.

**Comment by jkloetzke** [comment]
Sure. But that needs to be implemented in Bob itself. I think I have it on some Todo list but feel free to open an issue at the Bob repo.
