### ISSUE TITLE
cmake: CMAKE_GENERATOR etc. to support windows

### ISSUE THREAD

**Issue by mahaase** [BobBuildTool/basement#24]
https://github.com/BobBuildTool/basement/blob/6878d4e8276588e353a7b962a32d9e1d22e8044a/classes/cmake.yaml#L83

for linux no need for that, but if we want to support windows too, we have to add `CMAKE_GENERATOR, CMAKE_GENERATOR_PLATFORM and CMAKE_GENERATOR_TOOLSET`.

may we should set `CMAKE_GENERATOR: "Unix Makefiles"` in default.yaml.

`CMAKE_GENERATOR, CMAKE_GENERATOR_PLATFORM and CMAKE_GENERATOR_TOOLSET` could be set by special windows toolchain yamls.

**Comment by jkloetzke** [comment]
Sure. Do you plan to send a pull request for this? And related to that shouldn't we then also add some windows toolchain recipes that define these variables?

**Comment by mahaase** [comment]
already merged. we can close this!

THX for that feature!
