### ISSUE TITLE
openssl: ${ARCH}-linux will not work for aarch64

### ISSUE THREAD

**Issue by mahaase** [BobBuildTool/basement#37]
Hi.

https://github.com/BobBuildTool/basement/blob/cfc1360a853461b868b8157704225527fe2e6b30/recipes/libs/openssl.yaml#L35

value for ARCH is "arm64" for aarch64 systems.
This will not work with openssl profiles: https://github.com/openssl/openssl/blob/master/Configurations/10-main.conf#L764

We have to use "linux-aarch64".

BR.

**Comment by jkloetzke** [comment]
Yes. Needs to be fixed.

**Comment by mahaase** [comment]
could we also fix, that the stuff will be built statically for host-usage, like default for autotools a.s.o.?!

**Comment by jkloetzke** [comment]
Sure. Patches are welcome. :)

**Comment by mahaase** [comment]
we should wait for openssl 1.1.1i: https://github.com/openssl/openssl/pull/13218
this fix is important to get aarch64 static builds done.
I will create a patch soon.
