### ISSUE TITLE
forward python for ninja build

### ISSUE THREAD

**Issue by mahaase** [BobBuildTool/basement#40]
Hi.

Ninja needs python in buildScript:

https://github.com/BobBuildTool/basement/blob/a9d3036eae50278b5e5dfad3bbafd00a649e2621/recipes/devel/ninja.yaml#L14

but there is no python tool forwarded in rootrecipe:

https://github.com/BobBuildTool/basement/blob/a9d3036eae50278b5e5dfad3bbafd00a649e2621/classes/basement/rootrecipe.yaml#L44

BR.

**Comment by jkloetzke** [comment]
Did you have a build failure or was it just an observation?

Python is assumed to be available one the host and is also installed in the sandbox image. The `python::python3-minimal` tool is only used during sandbox builds.

**Comment by mahaase** [comment]
yep.

/usr/bin/env python: no such file or directory.

**Comment by jkloetzke** [comment]
With or without sandbox? It could be that `/usr/bin/env` is missing or `python` is not in `$PATH`...

**Comment by mahaase** [comment]
build withour sandbox. no "python", just "python3".

**Comment by mahaase** [comment]
adding python3-minimal in front of ninja failes with that one:
https://stackoverflow.com/questions/59618277/python3-cross-compilation-make-failure 

no idea how to fix that.

**Comment by jkloetzke** [comment]
No, trying to add python3-minmal is not the right approach. Even if you could build meson it might later fail for the same reason when trying to invoke it. Either we call `python3` directly or we require that `python` is available on the host. In the sandbox it is explicitly done this way.

So replacing

    "$1/configure.py" --bootstrap

with

    python3 "$1/configure.py" --bootstrap

might be the simplest solution...

**Comment by mahaase** [comment]
okay. for this use-case i am fine with (BUT i dont understand, why we shouldnt use a self-built python3 host tool). 

i try to port our recipes by using the basement now!

here we need a python3 host module. because we have python generators we provide with bob, so we also want to provide the python3 tool too. for me, it is not possible to build a host python tool with the host-toolchain (because of the issue above).

but this is maybe a different ticket?!

**Comment by jkloetzke** [comment]
I don't quite understand. On the host python3 is already required because you use Bob. In the sandbox python3 is also available. What is missing is the standard "python" executable that *should* point to python3 nowadays but used to be python2 on many systems. Apparently on your distro it is missing altogether. I consider it a problem of the meson package to require an unqualified python version which asks for trouble IMHO.

Python3 cannot easily be provided as self-built tool. It is not really relocatable, depends on the host system for various native libraries (openssl, sqlite, ...) and won't work for many modules. The `python3-minimal` is just sufficient for the build process of the basement sandbox.

> because we have python generators we provide with bob, so we also want to provide the python3 tool too. for me, it is not possible to build a host python tool with the host-toolchain (because of the issue above).

I'm afraid I do not understand what you try to say with the above...

**Comment by mahaase** [comment]
> Python3 cannot easily be provided as self-built tool. It is not really relocatable, depends on the host system for various native libraries (openssl, sqlite, ...) and won't work for many modules. The `python3-minimal` is just sufficient for the build process of the basement sandbox.
> 
> > because we have python generators we provide with bob, so we also want to provide the python3 tool too. for me, it is not possible to build a host python tool with the host-toolchain (because of the issue above).
> 
> I'm afraid I do not understand what you try to say with the above...

Yea, python is not relocatable out of the box. But we have a package, with a fix python3 version. than we install some additional modules with pip into --root dir and collect this paths and export them into `PYTHONPATH`. so python will find all this additional modules, that are necessary for our python generators.

this will not work, if everyone will have its own python3 version (becuase the version number will be part of the path-name).
the same works also for us with windows. there we use the windows python embed version.

**Comment by jkloetzke** [comment]
Ok, understood. But this is then a separate ticket, right? Building a relocatable python is currently not supported by basement but that can be merged...

**Comment by daxcore** [comment]
https://github.com/BobBuildTool/basement/pull/43
