### ISSUE TITLE
cmake not build with BASEMENT_HOST_COMPAT_TOOLCHAIN: "0"

### ISSUE THREAD

**Issue by mahaase** [BobBuildTool/basement#41]
cmake not build with BASEMENT_HOST_COMPAT_TOOLCHAIN: "0"

just for me?

```
/home/mhaase/ws/fdt.bobrecipes/dev/dist/libs/libuv-dev/x86_64-bob-linux-gnu/1/workspace/usr/lib/libuv.a(libuv_la-fs.o): In function `uv__mkostemp_initonce':
/home/mhaase/ws/fdt.bobrecipes/dev/src/libs/libuv/1/workspace/src/unix/fs.c:280: undefined reference to `dlsym'
/home/mhaase/ws/fdt.bobrecipes/dev/src/libs/libuv/1/workspace/src/unix/fs.c:286: undefined reference to `dlerror'
collect2: error: ld returned 1 exit status
[456/520] Linking CXX static library Source/libCMakeServerLib.a
[457/520] Linking CXX executable bin/ctest
[458/520] Building CXX object Tests/CMakeLib/CMakeFiles/CMakeLibTests.dir/testArgumentParser.cxx.o
[459/520] Building CXX object Tests/CMakeLib/CMakeFiles/CMakeLibTests.dir/testCTestBinPacker.cxx.o
[460/520] Building CXX object Tests/CMakeLib/CMakeFiles/CMakeLibTests.dir/testCTestResourceAllocator.cxx.o
ninja: build stopped: subcommand failed.
++ bob_handle_error 1
++ set +x
Step failed with return status 1; Command: ninja ${MAKE_JOBS:+-j "${MAKE_JOBS}"} "$@"
```

**Comment by jkloetzke** [comment]
I've never tested `BASEMENT_HOST_COMPAT_TOOLCHAIN=0` to be honest. What did you try to build? I'll look at it in the evening...

**Comment by jkloetzke** [comment]
Works for me (on Debian GNU/Linux 10 (buster)):

```
$ cd tests/linux
$ bob dev -DBASEMENT_HOST_COMPAT_TOOLCHAIN=0 buildall/devel::cmake -j
```

Either your host misses some development packages or something else is broken for your system.

But why do you build with BASEMENT_HOST_COMPAT_TOOLCHAIN=0? Do you need to build with some special host compiler or libraries?

**Comment by daxcore** [comment]
i am not really interested into this, this was just a try to get python3 buildable. with my private machine, i got this now.
let's close this ticket. thanks so fare. i should check my office-pc.

**Comment by jkloetzke** [comment]
Ok, then I'll close it. Feel free to reopen if you suspect an error in the recipes for builds without a compatibility toolchain...
