### ISSUE TITLE
my shared libraries will not be installed

### ISSUE THREAD

**Issue by mahaase** [BobBuildTool/basement#54]
https://github.com/BobBuildTool/basement/blob/f4a53e1d7b9e8f1ac4d9e3c65a70a97d5c6bd03e/classes/install.yaml#L140

could we change this line to just: `/usr/lib/ "/usr/lib/*.so*" \`
so it would also match with our normal libs, built by CMake.

**Comment by jkloetzke** [comment]
No, I would prefer to keep it this way.

The rationale is that `installPackageLib` should install all shared libraries that need to be installed when running applications that depend on them. Proper shared libraries should have at least a major version number that is part of the file name, e.g. `libfoo.so.1`. The pure `*.so` files are the *development* versions that are *not* intended to be installed on the target.

There are two possible solutions:

1. Fix your CMake recipes to set a `SOVERSION` property on the library target. If in doubt use `0`.
2. Patch or wrap the install class in your local version

**Comment by mahaase** [comment]
👍 btw: thx. setting the `SOVERSION` in our cmake-macro-library was an easy job and works like expected now.
