### ISSUE TITLE
repatching doesn't work for iterative patches

### ISSUE THREAD

**Issue by mahaase** [BobBuildTool/basement#55]
if the order of patchfiles is relevant, the revert patching doesn't work:

https://github.com/BobBuildTool/basement/blob/f4a53e1d7b9e8f1ac4d9e3c65a70a97d5c6bd03e/classes/patch.yaml#L26-L48

I guess, we have to write the patches in reverted order into the `.applied` file?!

**Comment by jkloetzke** [comment]
Actually I wanted to properly solve this issue by BobBuildTool/bob#347. The whole patch class is a stop-gap solution...
