### ISSUE TITLE
Licensing question

### ISSUE THREAD

**Issue by Ferruck** [BobBuildTool/basement#7]
I just want to open up this point for discussion: The whole recipe stack is licensed as GPLv3+, so far no problems. But what about the patches provided alongside the recipes? I guess most of them are just taken from upstream and published here for convenience reasons, but cannot be simply re-licensed to GPLv3+, or? I guess clarifying the origin and license on a per-patch basis is a must for adoption of this basement layer because a re-licensing of the patches - and thus of the built software (at least in parts) - to GPLv3+ would de-facto prohibit commercial use. We'd need a *maintainable* way of tracking both origin and license on a per-patch basis, though.

Any input and opinions appreciated.

**Comment by jkloetzke** [comment]
I think we have to go the buildroot route. In the end this means GPLv2(+) with a patch exception:

```
With the exceptions below, Buildroot is distributed under the terms of
the GNU General Public License, reproduced below; either version 2 of
the License, or (at your option) any later version.

Some files in Buildroot contain a different license statement. Those
files are licensed under the license contained in the file itself.

Buildroot also bundles patch files, which are applied to the sources
of the various packages. Those patches are not covered by the license
of Buildroot. Instead, they are covered by the license of the software
to which the patches are applied. When said software is available
under multiple licenses, the Buildroot patches are only provided under
the publicly accessible licenses.
```

Going back to GPLv2 would enable more compatibility. As this repository is meant to be used as layer we should probably also make an explicit statement that this is allowed even if the using repository is under an incompatible license. Something like the the Linux syscall exception:

```
   NOTE! This copyright does *not* cover user programs that use kernel
 services by normal system calls - this is merely considered normal use
 of the kernel, and does *not* fall under the heading of "derived work".
```

What do you think?

**Comment by Ferruck** [comment]
Sounds reasonable. The only problem is to phrase this more or less waterproof.

But why go back to GPLv2? If you add the necessary exceptions, anyways, why not stick with GPLv3?

**Comment by jkloetzke** [comment]
> Sounds reasonable. The only problem is to phrase this more or less waterproof.

I think the buildroot text could be taken as-is. Phrasing a "linking" waiver is a problem, though.

> But why go back to GPLv2? If you add the necessary exceptions, anyways, why not stick with GPLv3?

The rationale is that GPLv3+ is basically incompatible to anything. Plus the problem that no company would base their recipes on GPLv3 stuff. Using GPLv2 with a layering exception could be enough to foster adoption.

I'm also thinking about MIT. This makes the basement layer compatible to almost anything. OTOH we could not simply port stuff from busybox anymore. Not an easy answer...

**Comment by Ferruck** [comment]
I'm voting for staying as copyleft as possible with just as many exceptions as necessarily needed. If this is GPLv2+ with the Buildroot additions and a yet-to-author linking waiver, be it. In other words: I'd rather not use MIT.

**Comment by jkloetzke** [comment]
Understood. I'll prepare something. AFAICS you are the only contributor so far. So as long as we agree re-licensing the recipes should not be an issue.
