### ISSUE TITLE
missing __unset__ case?

### ISSUE THREAD

**Issue by mahaase** [BobBuildTool/basement#76]
https://github.com/BobBuildTool/basement/blob/692481ffd18e227ab83b6312911e1bad6362b67d/classes/cmake.yaml#L63-L70

should we use `__unset__` to define a default by just adding

```
__unset__)
   ;;
```

**Comment by jkloetzke** [comment]
The `cpackageLibraryType` function only returns `shared`, `static` or `both`. It will never return `__unset__`. The `__unset__` stuff was hidden in `classes/cpackage.yaml` on one of the last refactorings.
