### ISSUE TITLE
[improvement] target-toolchain not available in build-shell

### ISSUE THREAD

**Issue by mahaase** [BobBuildTool/basement#95]
https://github.com/BobBuildTool/basement/blob/6115d59782f0b2f89b5cf87922ac5b6da949302d/classes/cpackage.yaml#L16-L18

```diff
- buildScript: |
+ buildSetup: |
    # Check if we're officially cross-compiling
    cpackageCrossCompiling()
```

I would prefer to use the new `buildSetup `stuff here, wouldn't that a good idea?
So the e.g. CL also would be available in `build.sh shell`.

update: if we do this for ?all? classes, we also could call the functions inside the shell, like `cmakeBuild`.

**Comment by jkloetzke** [comment]
Yes, this is a good idea.
